name: generate podcast feeds2
on:
  push:
    branches:
      - main  # Adjust this to your desired branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: run feed generator
        uses: rabiejavadian/podcast-generator@main
